# Generated by Django 5.0.2 on 2024-03-05 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=14)),
                ("message", models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("number", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=50)),
                ("password", models.CharField(max_length=6)),
                ("confirm_password", models.CharField(max_length=50)),
                ("role", models.CharField(default="users", max_length=50)),
                ("status", models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nephrologist", models.CharField(max_length=100)),
                ("eye_care", models.CharField(max_length=100)),
                ("pediatrician_clinic", models.CharField(max_length=100)),
                ("parental_care", models.CharField(max_length=200)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptoms", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("dob", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=50)),
                ("days_of_treatment", models.CharField(max_length=50)),
                ("fees", models.CharField(max_length=50)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.users"
                    ),
                ),
            ],
        ),
    ]
