# Generated by Django 5.0.2 on 2024-03-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_delete_contact_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("contact_no", models.CharField(max_length=50)),
                ("message", models.TextField(max_length=200)),
            ],
        ),
    ]
